version: '3.8'

services:
  carabase:
    build: .
    container_name: carabase
    ports:
      - "3000:3000"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    environment:
      - NODE_ENV=production
      - PORT=3000
      # - DB_ENCRYPTION_KEY=your_encryption_key_here
      # - TOKEN_TTL_DEFAULT=1d
